#!/usr/bin/env bash
# Embed Web UI assets: minify (optional), gzip, xxd -i -> src/gateway/ui_assets.h
# Input: web/index.html, web/hardware.html, web/css/style.css,
#        web/js/dashboardView.js + web/js/app.js (concatenated),
#        web/js/hardwareView.js (hardware page bundle)
# Output: src/gateway/ui_assets.h with named arrays and lookup table
# Verify: total gzipped < 50 KB

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WEB_DIR="$PROJECT_ROOT/web"
OUT_HEADER="$PROJECT_ROOT/src/gateway/ui_assets.h"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

# Optional minimal minify: collapse multiple spaces (safe for CSS/JS)
minify_sed() {
    sed -e 's/[[:space:]]\+/ /g' \
        -e 's/^[[:space:]]*//' \
        -e 's/[[:space:]]*$//' \
        "$@"
}

process_file() {
    local src="$1"
    local dst="$2"
    local var_base="$3"
    if [ ! -f "$src" ]; then
        echo "Error: $src not found" >&2
        exit 1
    fi
    # Optional minimal minify for CSS/JS; HTML left as-is to avoid breaking structure
    case "$src" in
        *.html) cp "$src" "$TMP_DIR/$dst" ;;
        *.css)  minify_sed "$src" > "$TMP_DIR/$dst" ;;
        *.js)   minify_sed "$src" > "$TMP_DIR/$dst" ;;
        *)      cp "$src" "$TMP_DIR/$dst" ;;
    esac
    gzip -c -9 "$TMP_DIR/$dst" > "$TMP_DIR/${var_base}_gz.bin"
    (cd "$TMP_DIR" && xxd -i "${var_base}_gz.bin") | \
        sed "s/unsigned char ${var_base}_gz_bin/unsigned char ${var_base}_gz/" | \
        sed "s/unsigned int ${var_base}_gz_bin_len/unsigned int ${var_base}_gz_len/"
}

mkdir -p "$(dirname "$OUT_HEADER")"
process_file "$WEB_DIR/index.html" "index.html" "ui_index_html" > "$TMP_DIR/index_html.txt"
process_file "$WEB_DIR/hardware.html" "hardware.html" "ui_hardware_html" > "$TMP_DIR/hardware_html.txt"
process_file "$WEB_DIR/css/style.css" "style.css" "ui_style_css" > "$TMP_DIR/style_css.txt"
cat "$WEB_DIR/js/dashboardView.js" "$WEB_DIR/js/app.js" > "$TMP_DIR/app_bundle.js"
process_file "$TMP_DIR/app_bundle.js" "app.js" "ui_app_js" > "$TMP_DIR/app_js.txt"
process_file "$WEB_DIR/js/hardwareView.js" "hardware.js" "ui_hardware_js" > "$TMP_DIR/hardware_js.txt"

# Compute total size and verify < 50 KB
TOTAL=0
for f in "$TMP_DIR"/*_gz.bin; do
    [ -f "$f" ] || continue
    TOTAL=$((TOTAL + $(wc -c < "$f")))
done
if [ "$TOTAL" -gt 51200 ]; then
    echo "Error: total gzipped size $TOTAL bytes exceeds 50 KB (51200)" >&2
    exit 1
fi

# Generate header
{
    echo "/* Auto-generated by scripts/embed_ui.sh - do not edit */"
    echo "#ifndef SHELLCLAW_UI_ASSETS_H"
    echo "#define SHELLCLAW_UI_ASSETS_H"
    echo ""
    echo "#include <stddef.h>"
    echo ""
    cat "$TMP_DIR/index_html.txt"
    echo ""
    cat "$TMP_DIR/style_css.txt"
    echo ""
    cat "$TMP_DIR/app_js.txt"
    echo ""
    cat "$TMP_DIR/hardware_html.txt"
    echo ""
    cat "$TMP_DIR/hardware_js.txt"
    echo ""
    echo "struct ui_asset_entry {"
    echo "    const char *path;"
    echo "    const unsigned char *ptr;"
    echo "    size_t len;"
    echo "    const char *content_type;"
    echo "};"
    echo ""
    echo "static const struct ui_asset_entry ui_asset_table[] = {"
    echo "    { \"/\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/index.html\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/chat\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/config\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/skills\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/memory\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/sessions\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/cron\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/logs\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/asap\", ui_index_html_gz, sizeof(ui_index_html_gz), \"text/html\" },"
    echo "    { \"/hardware\", ui_hardware_html_gz, sizeof(ui_hardware_html_gz), \"text/html\" },"
    echo "    { \"/hardware.html\", ui_hardware_html_gz, sizeof(ui_hardware_html_gz), \"text/html\" },"
    echo "    { \"/css/style.css\", ui_style_css_gz, sizeof(ui_style_css_gz), \"text/css\" },"
    echo "    { \"/js/app.js\", ui_app_js_gz, sizeof(ui_app_js_gz), \"application/javascript\" },"
    echo "    { \"/js/hardware.js\", ui_hardware_js_gz, sizeof(ui_hardware_js_gz), \"application/javascript\" },"
    echo "    { NULL, NULL, 0, NULL }"
    echo "};"
    echo ""
    echo "#endif /* SHELLCLAW_UI_ASSETS_H */"
} > "$OUT_HEADER"

echo "Generated $OUT_HEADER (total gzipped: $TOTAL bytes)"
