#!/usr/bin/env bash
# Run the upstream asap-compliance pytest harness against a live ShellClaw gateway.
#
# Deviations, v1.0 stance, and env reference: docs/ASAP.md § "ASAP compliance harness".
#
# Usage:
#   ./scripts/run_asap_compliance.sh
#   ./scripts/run_asap_compliance.sh http://127.0.0.1:18789
#   ASAP_AGENT_URL=http://127.0.0.1:18789 ./scripts/run_asap_compliance.sh
#
# Environment:
#   ASAP_AGENT_URL              agent base URL (default: http://127.0.0.1:18789)
#   ASAP_COMPLIANCE_SKIP_PIP=1  skip pip install when asap-compliance is already installed
#   ASAP_COMPLIANCE_PIP_USER=1  use "pip install --user" (prints a note when set)
#   ASAP_COMPLIANCE_VERSION     pip spec (default: asap-compliance>=1.0.0)
#   ASAP_COMPLIANCE_SKIP_HEALTH=1  skip /health probe before pytest
#   ASAP_COMPLIANCE_LIVE_TEST_DIR   directory for generated live pytest (default: temp)
#
# Prerequisites: python3 + pip (3.13+); gateway listening at ASAP_AGENT_URL (start shellclaw
# with [gateway] enabled — see config.example.toml port 18789). This script does not
# boot the agent; use scripts/dump_manifest.sh if you need an ephemeral local gateway.
#
# Exit codes: 0 pytest green, 1 usage/deps, 2 pip install failed, 3 agent unreachable,
#             4 pytest failed.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEFAULT_URL="http://127.0.0.1:18789"
AGENT_URL="${ASAP_AGENT_URL:-${DEFAULT_URL}}"
PIP_SPEC="${ASAP_COMPLIANCE_VERSION:-asap-compliance>=1.0.0}"

usage() {
	sed -n '2,21p' "$0" | sed 's/^# \{0,1\}//'
	exit 1
}

while [[ $# -gt 0 ]]; do
	case "$1" in
	-h | --help) usage ;;
	-*)
		echo "run_asap_compliance: unknown option: $1" >&2
		usage
		;;
	*)
		AGENT_URL="$1"
		shift
		;;
	esac
done

export ASAP_AGENT_URL="${AGENT_URL}"

if ! command -v python3 >/dev/null 2>&1; then
	echo "run_asap_compliance: python3 not found (required for asap-compliance; Python 3.13+ recommended)" >&2
	exit 1
fi

if ! python3 -m pip --version >/dev/null 2>&1; then
	echo "run_asap_compliance: pip not available (install python3-pip or ensure pip is on PATH)" >&2
	exit 1
fi

if [[ "${ASAP_COMPLIANCE_SKIP_PIP:-}" != "1" ]]; then
	echo "==> pip install ${PIP_SPEC}"
	if [[ "${ASAP_COMPLIANCE_PIP_USER:-}" == "1" ]]; then
		echo "run_asap_compliance: using pip install --user (ensure ~/.local/bin is on PATH for pytest)" >&2
		python3 -m pip install --user --quiet "${PIP_SPEC}" || {
			echo "run_asap_compliance: pip install failed" >&2
			exit 2
		}
	else
		if ! python3 -m pip install --quiet "${PIP_SPEC}" 2>&1; then
			echo "run_asap_compliance: pip install failed (PEP 668? use a venv: python3 -m venv .venv-asap && source .venv-asap/bin/activate)" >&2
			exit 2
		fi
	fi
else
	echo "==> pip install skipped (ASAP_COMPLIANCE_SKIP_PIP=1)"
	if ! python3 -c "import asap_compliance" 2>/dev/null; then
		echo "run_asap_compliance: asap_compliance not importable; unset ASAP_COMPLIANCE_SKIP_PIP or install manually" >&2
		exit 1
	fi
fi

if ! python3 -m pytest --version >/dev/null 2>&1; then
	echo "run_asap_compliance: pytest not available after install (check pip / PATH)" >&2
	exit 1
fi

health_url="${AGENT_URL%/}/health"
if [[ "${ASAP_COMPLIANCE_SKIP_HEALTH:-}" != "1" ]]; then
	if ! command -v curl >/dev/null 2>&1; then
		echo "run_asap_compliance: curl not found; set ASAP_COMPLIANCE_SKIP_HEALTH=1 to skip probe" >&2
		exit 1
	fi
	code="$(curl -sS -o /dev/null -w '%{http_code}' --connect-timeout 2 --max-time 5 "${health_url}" 2>/dev/null || echo 000)"
	if [[ "${code}" != "200" ]]; then
		echo "run_asap_compliance: ${health_url} not healthy (HTTP ${code})" >&2
		echo "run_asap_compliance: start the ShellClaw gateway first, e.g.:" >&2
		echo "  make shellclaw && ./build/shellclaw   # with [gateway] enabled in config" >&2
		echo "  or: MANIFEST_DUMP_SKIP_START=0 ./scripts/dump_manifest.sh   # ephemeral gateway on ${DEFAULT_URL}" >&2
		exit 3
	fi
	echo "==> agent health OK (${health_url})"
fi

LIVE_TEST_DIR="${ASAP_COMPLIANCE_LIVE_TEST_DIR:-$(mktemp -d)}"
cleanup_live_test() {
	[[ -n "${ASAP_COMPLIANCE_LIVE_TEST_DIR:-}" ]] && return 0
	[[ -d "${LIVE_TEST_DIR}" ]] && rm -rf "${LIVE_TEST_DIR}"
}
trap cleanup_live_test EXIT

mkdir -p "${LIVE_TEST_DIR}"
cat >"${LIVE_TEST_DIR}/test_shellclaw_live.py" <<'PY'
"""Live ASAP compliance checks against ShellClaw (generated by run_asap_compliance.sh)."""

from __future__ import annotations

import pytest

from asap_compliance.validators.handshake import validate_handshake
from asap_compliance.validators.sla import validate_sla
from asap_compliance.validators.state import validate_state_machine


@pytest.mark.asap_compliance
def test_live_handshake(compliance_harness) -> None:
    result = validate_handshake(compliance_harness)
    failed = [c for c in result.checks if not c.passed]
    assert result.passed, "; ".join(f"{c.name}: {c.message}" for c in failed)


@pytest.mark.asap_compliance
def test_live_state_machine(compliance_harness) -> None:
    result = validate_state_machine(compliance_harness)
    failed = [c for c in result.checks if not c.passed]
    assert result.passed, "; ".join(f"{c.name}: {c.message}" for c in failed)


@pytest.mark.asap_compliance
def test_live_sla(compliance_harness) -> None:
    result = validate_sla(compliance_harness)
    failed = [c for c in result.checks if not c.passed]
    assert result.passed, "; ".join(f"{c.name}: {c.message}" for c in failed)
PY

echo "==> pytest asap-compliance (-m asap_compliance) against ${AGENT_URL}"
# Upstream CLI: pytest --asap-agent-url=<url> -m asap_compliance (PyPI wheel ships library only).
python3 -m pytest \
	--asap-agent-url="${AGENT_URL}" \
	-m asap_compliance \
	-v \
	"${LIVE_TEST_DIR}" \
	|| exit 4

echo "==> run_asap_compliance: all checks passed"
